version: '3'
services:
  postgres:
    container_name: demo-postgres
    image: postgres:9.6
    environment:
      - POSTGRES_USER=waq
      - POSTGRES_PASSWORD=demo
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
